services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_URI=mongodb://db:27017/shop
      - SESSION_SECRET=P@ssw@rd
      - GOOGLE_CLIENT_ID=placeholder_id
      - GOOGLE_CLIENT_SECRET=placeholder_secret
      - GITHUB_CLIENT_ID=placeholder_id
      - GITHUB_CLIENT_SECRET=placeholder_secret
    depends_on:
      - db
  db:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
